services:
  evobot:
    env_file:
      - .env
    image: evo:${VERSION}
    container_name: evobot
    hostname: evobot
    ports:
      - ${EVO_PORT}:24916
    volumes:
      - ${VOLUME_DIR}/log/EvoBot.log:/opt/evobot/EvoBot.log
      - ${VOLUME_DIR}/config/config.yaml:/opt/evobot/config.yaml
    restart: always
    networks:
      - evo_net